### ISSUE TITLE
Master branch not working as expected

### ISSUE THREAD

**Issue by rchampourlier** [fabien-d/alertify.js#124]
Hi,

First: thanks for this nice library.

I started testing, added the repo as a submodule to my project, referencing 'master' by default. Added the necessary require lines, everything was included, but the API is just not the same: no global 'alertify'.

Changed my submodule reference to 0.3.8, and this works as expected. You may just want to make your 'master' branch work, this would be simple when we come and try!

Cheers!

**Comment by fabien-d** [comment]
Thanks for the note, I've been meaning to update the docs, but haven't had time to fully do them. The master branch is currently at `0.4.0rc1` and the API has changed which is why it doesn't work as expected.

The `master` branch is tagged at versions to ensure it works as expected at that point, but using `master` as in may sometimes result in unexpected behaviour.

To use the master branch, you need to follow the new [API documentation](https://github.com/fabien-d/alertify.js/wiki/0.4.*-API-Documentation) which currently isn't available (in progress), but you can checkout the [example site](http://fabien-d.github.com/alertify.js/0.4.0rc1/) to see the usage.
