### ISSUE TITLE
grunt build produces some errors

### ISSUE THREAD

**Issue by akarelas** [fabien-d/alertify.js#185]
It says I need to have Ruby and Compass installed to do `grunt build`.

Do I really need to? If I just type grunt build -f, will I be ok?

```
bugs@bugs-vm:~/fromGit/alertify.js$ grunt build
Running "jshint:files" (jshint) task
>> 10 files lint free.

Running "qunit:all" (qunit) task
Testing test/index.html..............................OK
>> 122 assertions passed (80ms)

Running "clean:build" (clean) task

Running "generateinit:build" (generateinit) task

Running "requirejs:compile" (requirejs) task

Tracing dependencies for: alertify

src/alertify.js
----------------
src/proto.js
src/alertify.js
src/validate.js
src/element.js
src/transition.js
src/keys.js
src/dialog.js
src/log.js
src/logs.js
tmp/alertify.init.js


Running "copy:build" (copy) task
Copied 1 files

Running "clean:postbuild" (clean) task
Cleaning "build"...OK
Cleaning "tmp"...OK

Running "stripdefine:build" (stripdefine) task

Running "compass:dist" (compass) task
Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

Aborted due to warnings.
```

**Comment by fabien-d** [comment]
Ruby and Compass are needed to compile `Sass` into `CSS`. If you just cloned the project - I would suggest you checkout the `0.3` branch (https://github.com/fabien-d/alertify.js/tree/0.3) since that is latest stable release.

Master currently points to `0.4.0rc1` which will never be done. I'm skipping that release and going straight to [0.5.0](https://github.com/fabien-d/alertify.js/pull/173).

In the `0.3.*` release, there is no Sass so you will not need ruby or compass.

**Comment by akarelas** [comment]
thanks

**Comment by fabien-d** [comment]
Closing - feel free to reopen if this didn't solve your issue.
