### ISSUE TITLE
library cannot be loaded prior to body creation

### ISSUE THREAD

**Issue by veracarr** [fabien-d/alertify.js#21]
it would be great if your library could be loaded at any time; i would prefer to have it loaded in the head section. it looks like the way it's currently written, it must be included only after the body is loaded, e.g. in the body section. would it be possible to supply a method call which does your initialization, so i can call it later, such as with jquery's ready callback?

other than tracking down this one issue, this library was extremely easy for me to get running and customized. looks great. thanks!

**Comment by fabien-d** [comment]
This was being discussed in pull request https://github.com/fabien-d/alertify.js/pull/10. The request was to add a DOM loaded event, which I'm still not sure is the right approach for this project since most people already have a library to do this (e.g. jQuery)...

I was thinking of 2 options (code examples are just for visual purposes):
- expose the init method in the API meaning it would have to be initiated before use

``` js
// initialize after DOM ready
alertify.init();

// use
alertify.alert("...");
```
- check the first time alertify is used to see if it's already been initialized. That way it doesn't change the current usage but prevents alertify from trying to create DOM elements before it's told to.

``` js
// maybe in the dialog method
if (typeof init === "function") init();

// and have the init method delete itself after first use
init = function () {
    ...
    delete this.init;
}
```

I'd love to get some input on it.

**Comment by drazion** [comment]
Just as an aside, you may want to consider making the body requirement a little more apparent in the docs. Although I was able to figure this out fairly quickly, specifically when I saw n.body is null, it was not immediately clear that alertify.js needs to be in the body.  But otherwise implementing it was a breeze.

To your point above, I like that it's not put into the DOM until I need it.  On the page where I use it, I'm already relying on the client to parse a good deal of code and determine the layout, so for me at least, this is a great feature.

**Comment by fabien-d** [comment]
Documentation updates are a priority this weekend - mainly around usage, code contribution guidelines ...

**Comment by lightswitch05** [comment]
Looking forward to this fix since Ruby On Rails automatically includes javascript in the `<head>`

**Comment by fabien-d** [comment]
Fixed with ^ pull request

**Comment by veracarr** [comment]
hi Fabien,

this fixed my problem. thank you!!

vera
