### ISSUE TITLE
Feature request: Ability to control button on .alert()

### ISSUE THREAD

**Issue by peterbe** [fabien-d/alertify.js#51]
I use the `alertify.alert(...)` to display a form submission error. By default it displays with a **green** OK button. I would love to be able to override that so it could be a red button instead since that will have a better visual indication.

**Comment by fabien-d** [comment]
Is this a unique instance request, where you can use multiple alerts but change/override any specific one OR a generic override for all buttons?

if the latter, a CSS overwrite would do

``` css
.alertify-button-ok { ... }
```

otherwise, maybe adding an optional parameter that allows a custom class for any dialog would be beneficial?

### JavaScript

``` js
alertify.alert("Message", callback, "custom-class");
```

### CSS

``` css
.alertify-dialog-custom-call { ... }
```

**Comment by peterbe** [comment]
It would only be for specific instances. Your example looks like it would definitely work.

**Comment by fabien-d** [comment]
I can see this being useful, I'll have to think about the approach/implementation that makes the most sense... I want to be careful not overdoing the optional parameters.

Suggestions are welcomed.

**Comment by fabien-d** [comment]
will be part of the 0.3.0 release. usage:

``` js
alertify.alert("message", function () {}, "css_class");
alertify.confirm("message", function () {}, "css_class");
alertify.prompt("message", function () {}, "placeholder", "css_class");
```
