### ISSUE TITLE
Subclassing?

### ISSUE THREAD

**Issue by heston** [fabien-d/alertify.js#70]
First off, I have to say that I really like alertify. It provides a great baseline of functionality and is easy to use. However, during the course of a project, I found myself wanting to add additional functionality to alertify -- such as rendering different HTML in some cases, or adding a "close" button in the upper right. This sort of stuff is definitely outside the scope of alertify's core usage. So, what's a guy to do? Subclass and overload! It would be awesome to simply inherit from alertify, overload the build method, and do whatever I wanted.

Unfortunately, the architecture of alertify does not allow that. Everything inside the constructor is a private method or property (http://javascript.crockford.com/private.html), so it's impossible to access these in inheriting classes. I know it's a big job to refactor alertify into a inheritance-friendly structure, but I thought I'd put it out there all the same.

**Comment by fabien-d** [comment]
Alertify is more aimed at replicating the native dialog which is why the public API is limited and only exposes the absolute required methods. I'm not sure if extending fits the description of what alertify.js tries to achieve.

For custom HTML or close buttons (to reuse your examples) falls more under a modal pattern, which many great libraries already offer.
