### ISSUE TITLE
Not working in Safari for Windows

### ISSUE THREAD

**Issue by helmutstrasser** [fabien-d/alertify.js#81]
Hi Fabien,

I tested your alertify in Safari for Windows 7 (Safari version 5.1.7). The popups are not shown (you can reproduce that with your own demo page). I can see them in the DOM, but they don't appear on the screen.
The funny thing is, that when I set the body to display:none and remove that property again, the popup comes up.

**Comment by fabien-d** [comment]
I'll keep this on the back burner and I'll try to take a look at it when I have access to a windows machine but it appears that Apple has (silently) stopped developing Safari for Windows. The last update (5.1.7) was in May 2012 and they've removed all direct download links on their website. With browser shares the way they are, unless it's an obvious error - I won't be spending too much time on it.

I'll gladly accept a PR with a fix (if it doesn't require a safari specific hack) but otherwise, unfortunately for the time being, it's going to be low on the list of priorities.

**Comment by helmutstrasser** [comment]
Wow, a super fast answer :)
I didn't know Safari is no longer supported. I verify, Apple didn't update their browser since May 2012.
Well, I totally agree, there is very low priority for this problem.
Thx and greets!

**Comment by fabien-d** [comment]
Don't quote me on "no longer supported"... but certainly appears going in that direction

**Comment by helmutstrasser** [comment]
I won't and don't :D

**Comment by fabien-d** [comment]
This issue should now be fixed. There was a CSS property that was conflicting with older versions of Safari. I've restructured a few things in ^ pull request.

**Comment by helmutstrasser** [comment]
Fabulous! I do confirm that it is working on Safari/Windows now. Thanks a lot!

**Comment by fabien-d** [comment]
Great! Closing issue
