### ISSUE TITLE
Chrome Canary: notifications not being removed from DOM.

### ISSUE THREAD

**Issue by jan-swiecki** [fabien-d/alertify.js#82]
Google Chrome Canary `Version 26.0.1370.0 canary`.

When I go to [http://fabien-d.github.com/alertify.js/](http://fabien-d.github.com/alertify.js/) and click `Notification` in `Customizable Log Messages` multiple times then few messages pop-up (expected behaviour).

After messages disappear from screen they are still inside DOM (checked with `Inspect element`) and when I click `Notification` again then new message shows in the middle, not bottom (because it stacks on top of not removed invisible messages).

**Comment by fabien-d** [comment]
The elements get removed once the `transitionend` event is triggered. There was a [bug regarding this issue](https://bugs.webkit.org/show_bug.cgi?id=105647) reported. At a quick glance it appears that it had been resolved in the canary build, but I'll take a closer look when I have a chance.

I wouldn't consider this a critical issue since the canary is an early adoption version and things may still change.

**Comment by jan-swiecki** [comment]
Thanks for answer!

> I wouldn't consider this a critical issue since the canary is an early adoption version and things may still change.

Indeed, but I thought it is worth mentioning here.

**Comment by fabien-d** [comment]
Definitely worth mentioning. I'll be keeping an eye on it. Cheers!

**Comment by fabien-d** [comment]
Appears to be resolved with stable release of chrome 26. Closing.
